default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: spree_shop_development

test:
  <<: *default
  database: spree_shop_development

production:
  <<: *default
  database: spree_shop_production